"""add column enabled in Vehicle

Revision ID: 3d1e9533ba68
Revises: 6c5b74caa36f
Create Date: 2025-09-10 11:17:15.209155

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d1e9533ba68"
down_revision = "6c5b74caa36f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enabled", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.drop_column("enabled")

    # ### end Alembic commands ###
