"""update: name of category unique

Revision ID: eb7ddb2ed0fa
Revises: 3d1e9533ba68
Create Date: 2025-09-16 17:29:21.956640

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "eb7ddb2ed0fa"
down_revision = "3d1e9533ba68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("license_categories", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("license_categories", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
